import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import worker from './index.js';
const sqlite = new DatabaseSync(':memory:');
sqlite.exec(readFileSync(new URL('./migrations/0001_bottles.sql', import.meta.url), 'utf8'));
const DB = { prepare(sql) { return { bind(...values) { const stmt = sqlite.prepare(sql); return { async first() { return stmt.get(...values) ?? null; }, async all() { return { results: stmt.all(...values) }; }, async run() { const r = stmt.run(...values); return { meta: { changes: r.changes } }; } }; } }; }, async batch(statements) { return Promise.all(statements.map(s => s.all())); } };
async function call(path, who = 'a', body, origin = 'http://localhost:8080') {
 return worker.fetch(new Request('http://test' + path, { method: body ? 'POST' : 'GET', headers: { Origin: origin, Authorization: 'Bearer ' + who.repeat(64), 'Content-Type': 'application/json', 'CF-Connecting-IP': who }, body: body ? JSON.stringify(body) : undefined }), { DB, ALLOWED_ORIGINS: 'http://localhost:8080' });
}
assert.equal((await call('/bottles/random', 'a', undefined, 'https://evil.test')).status, 403);
assert.equal((await call('/bottles/random', 'x')).status, 401);
assert.equal((await call('/bottles', 'a', {name:'A',message:'x'.repeat(301)})).status, 400);
const created = await call('/bottles', 'a', { name:' ', message:'你好 🌧️ <script>' }); assert.equal(created.status,201);
const {id} = await created.json();
const picked = (await (await call('/bottles/random')).json()).bottle;
assert.equal(picked.id, id);
assert.equal((await call(`/bottles/${id}/replies`,'a',{name:'A',message:'self'})).status,400);
assert.equal((await call(`/bottles/${id}/replies`,'b',{name:'B',message:'hello'})).status,201);
assert.equal((await call(`/bottles/${id}/replies`,'b',{name:'Changed',message:'again'})).status,409);
assert.equal((await call(`/bottles/${id}/replies`,'c',{name:'C',message:'another visitor'})).status,201);
const withReplies = (await (await call('/bottles/random','b')).json()).bottle;
assert.equal(withReplies.replies.length, 2);
assert.equal(withReplies.replies.every(reply => !reply.owner), true);
assert.equal((await call('/bottles/mine','a')).status, 404);
for(let i=0;i<20;i++) assert.equal((await call('/bottles','d',{name:'D',message:'test'})).status,201);
assert.equal((await call('/bottles','d',{name:'D',message:'limited'})).status,429);
sqlite.prepare('UPDATE bottles SET hidden=1 WHERE id=?').run(id);
assert.equal((await call(`/bottles/${id}/replies`,'e',{name:'E',message:'hidden'})).status,404);
console.log('Passed: validation, random discovery, all replies, reply uniqueness, no inbox endpoint, rate limit, hidden bottles.');
const round = [];
for (let i = 0; i < 20; i++) {
  const response = await call('/bottles/random', 'b', { seen: round });
  assert.equal(response.status, 200);
  const { bottle, restarted } = await response.json();
  assert.equal(restarted, false);
  assert.ok(!round.includes(bottle.id));
  round.push(bottle.id);
}
const restart = await (await call('/bottles/random', 'b', { seen: round })).json();
assert.equal(restart.restarted, true);
assert.ok(round.includes(restart.bottle.id));
assert.notEqual(restart.bottle.id, round.at(-1));
assert.equal((await call('/bottles/random', 'b', { seen: ['invalid'] })).status, 400);
sqlite.exec('UPDATE bottles SET hidden=1');
assert.equal((await (await call('/bottles/random', 'b', { seen: round })).json()).bottle, null);
sqlite.prepare('UPDATE bottles SET hidden=0 WHERE id=?').run(round[0]);
const single = await (await call('/bottles/random', 'b', { seen: [round[0]] })).json();
assert.equal(single.bottle.id, round[0]);
assert.equal(single.restarted, true);
const preflight = await worker.fetch(new Request('http://test/bottles/random', { method: 'OPTIONS', headers: { Origin: 'http://localhost:8080', 'Access-Control-Request-Method': 'POST', 'Access-Control-Request-Headers': 'authorization,content-type' } }), { DB, ALLOWED_ORIGINS: 'http://localhost:8080' });
assert.equal(preflight.status, 204);
assert.equal(preflight.headers.get('Access-Control-Allow-Origin'), 'http://localhost:8080');
console.log('Passed: full round without repeats, restart, no immediate repeat, invalid rounds, hidden/empty pool.');
